name = "GraphInvariants"
uuid = "1a60da4e-b1bc-4423-bff9-39362229c2d6"
authors = ["David Amos <somacdivad@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"

[compat]
julia = "1.6"
Graphs = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
